(define (problem robot_delivery_system)
(:domain neighborhood)
(:objects
robot0 - robot
robot0_init_iloc - location
cardboard_box_6 cardboard_box_7 cardboard_box_4 cardboard_box_5 cardboard_box_2 cardboard_box_3 cardboard_box_0 cardboard_box_1 - package
house_11 house_10 house_1 house_0 house_3 house_2 house_5 house_4 house_7 house_6 house_9 house_8 - house
cardboard_box_6_iloc cardboard_box_7_iloc cardboard_box_4_iloc cardboard_box_5_iloc cardboard_box_2_iloc cardboard_box_3_iloc cardboard_box_0_iloc cardboard_box_1_iloc - location
house_11_iloc house_10_iloc house_1_iloc house_0_iloc house_3_iloc house_2_iloc house_5_iloc house_4_iloc house_7_iloc house_6_iloc house_9_iloc house_8_iloc - location
n0 n25 n50 n75 n100 - weight
False True - binary
)
(:init
(Package_At cardboard_box_6 cardboard_box_6_iloc)
(Package_At cardboard_box_7 cardboard_box_7_iloc)
(Package_At cardboard_box_4 cardboard_box_4_iloc)
(Package_At cardboard_box_5 cardboard_box_5_iloc)
(Package_At cardboard_box_2 cardboard_box_2_iloc)
(Package_At cardboard_box_3 cardboard_box_3_iloc)
(Package_At cardboard_box_0 cardboard_box_0_iloc)
(Package_At cardboard_box_1 cardboard_box_1_iloc)
(House_At house_11 house_11_iloc)
(House_At house_10 house_10_iloc)
(House_At house_1 house_1_iloc)
(House_At house_0 house_0_iloc)
(House_At house_3 house_3_iloc)
(House_At house_2 house_2_iloc)
(House_At house_5 house_5_iloc)
(House_At house_4 house_4_iloc)
(House_At house_7 house_7_iloc)
(House_At house_6 house_6_iloc)
(House_At house_9 house_9_iloc)
(House_At house_8 house_8_iloc)
(Package_Size cardboard_box_6 n25)
(Package_To cardboard_box_6 house_5_iloc)
(Delivery_Status cardboard_box_6 False)
(Package_Size cardboard_box_7 n25)
(Package_To cardboard_box_7 house_11_iloc)
(Delivery_Status cardboard_box_7 False)
(Package_Size cardboard_box_4 n100)
(Package_To cardboard_box_4 house_2_iloc)
(Delivery_Status cardboard_box_4 False)
(Package_Size cardboard_box_5 n50)
(Package_To cardboard_box_5 house_0_iloc)
(Delivery_Status cardboard_box_5 False)
(Package_Size cardboard_box_2 n75)
(Package_To cardboard_box_2 house_3_iloc)
(Delivery_Status cardboard_box_2 False)
(Package_Size cardboard_box_3 n100)
(Package_To cardboard_box_3 house_6_iloc)
(Delivery_Status cardboard_box_3 False)
(Package_Size cardboard_box_0 n50)
(Package_To cardboard_box_0 house_7_iloc)
(Delivery_Status cardboard_box_0 False)
(Package_Size cardboard_box_1 n100)
(Package_To cardboard_box_1 house_10_iloc)
(Delivery_Status cardboard_box_1 False)
(Robot_At robot0 robot0_init_iloc)
(Robot_Load robot0 n0)
)
(:goal (forall (?package - package) (Delivery_Status ?package True)))
)